# Generated by Django 2.2.15 on 2020-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testjhgjhgjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='titleChanged',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
