# Generated by Django 2.2.15 on 2020-08-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200810_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='titleChanged',
            new_name='hjgfhjgjhjghj',
        ),
    ]
